name: MobItemDrops
main: kero.mobitemdrops.MobItemDrops
version: ${project.version}
commands:
    mobitemdrops:
        usage: /mobitemdrops
        aliases: mid
        description: MobItemDrops Commands.